from .domain import (
    University,
    Department,
    Program,
    StudentGroup,
    Room,
    Lecturer,
    Course,
    TimeSlot,
    Timetable,
    TimetableEntry,
    TimetableSnapshot,
    Constraint,
    TimetableTemplate,
    TemplateTimeBlock,
    lecturer_programs,
)

__all__ = [
    "University",
    "Department",
    "Program",
    "StudentGroup",
    "Room",
    "Lecturer",
    "Course",
    "TimeSlot",
    "Timetable",
    "TimetableEntry",
    "TimetableSnapshot",
    "Constraint",
    "TimetableTemplate",
    "TemplateTimeBlock",
    "lecturer_programs",
]
